org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1
minecraft_version_range=[26.1]
neo_version=26.1.0.7-beta

mod_id=donat_events
mod_name=Donat Events
mod_license=MIT
mod_version=0.5.0
mod_group_id=com.twilightfoxy.donatevents
mod_authors=Twily
mod_description=Base Donat Events mod.
